apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: gagafonov/microservices-demo:latest
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
